name = "dingyue-sdk-api"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "dingyue-sdk"
database_id = "20932182-dd69-435d-a734-65654e05f4e0"
migrations_dir = "src/db/migrations-d1"

[[r2_buckets]]
binding = "R2"
bucket_name = "dingyue-packages"

[[kv_namespaces]]
binding = "NONCE_CACHE"
id = "2c10068bab1e4d74846372b6139c7a26"

[vars]
# Non-sensitive config here.
# Sensitive config should be stored as secrets:
# wrangler secret put GA4_API_SECRET
# wrangler secret put FIREBASE_API_SECRET
CORS_ALLOWED_ORIGINS = "https://dingyue-sdk-admin.pages.dev"
